name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi 👋🏽, thank you for creating an Issue, we will review this and start working on it."
        pr-message: "Hi 👋🏽, thank you for contributing to this project, we will review your changes shortly."
